
[connections.snowflake]

account="QKHQOSA-HK55459"
user="vis"
role="DASH"
warehouse="COMPUTE_WH"
database="BANKER"
schema="PUBLIC"
private_key_path="/Users/rish88k/data_analysis/de_project/keys_/streamlit_key/private_key.pem"