name: 'banking_dbt'
version: '1.0.0'
config-version: 2

profile: 'bank_trans'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

models:
  banking_dbt:
    staging:
      +materialized: view  -- Staging models should be lightweight views
    marts:
      +materialized: table -- Final business models should be tables